language: node_js

node_js:
  - "0.11"

addons:
  code_climate:
    repo_token: 2bb2e70213bb0983d397cd3f9f8aaa8bcc740a0931191e9006d5a70af59eecf9

script:
  - npm run test-cov

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate

cache:
  directories:
    - node_modules
