language: node_js

node_js:
  - "0.11"

addons:
  code_climate:
    repo_token: 813ed63f61309afa14092c9928f9ffee8b7b4187b1c53b4d89048af8a1e06aa1

script:
  - npm run test-cov

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate

cache:
  directories:
    - node_modules
